version: '3'

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.29
    restart: always
    container_name: mysql
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    links:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.48.1 remote_port=9000"
      PHP_IDE_CONFIG: "serverName=Docker"
